const actionTypes = {
  GET_POSTS_SUCCESS: 'GET_POSTS_SUCCESS',
  GET_POSTS_FAIL: 'GET_POSTS_FAIL',
  CREATE_POST_SUCCESS: 'CREATE_POST_SUCCESS',
  UPDATE_POST_SUCCESS: 'UPDATE_POST_SUCCESS',
  DELETE_POST_SUCCESS: 'DELETE_POST_SUCCESS',
  LOG_USER_SUCCESS: 'LOG_USER_SUCCESS',
  LOG_OUT_USER_SUCCESS: 'LOG_OUT_USER_SUCCESS',
}

export default actionTypes